#!/usr/bin/env python3
"""Mirror www-feed Lane proposals into lanes.md Pending proposals.

Www harvests strategy proposals; does not write the business vault.

Usage:
  python3 scripts/www-lanes-sync.py           # apply (rewrite Pending if drift)
  python3 scripts/www-lanes-sync.py --check   # exit 1 on drift, no write
  python3 scripts/www-lanes-sync.py --json    # machine-readable result on stdout
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

WWW_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_FEED = Path(
    "/mnt/DataStore/Ventures/project-codex/codex-business/docs/www-feed.md"
)
DEFAULT_LANES = WWW_ROOT / ".cursor" / "lanes.md"

BEGIN = "<!-- www-lanes-sync:begin -->"
END = "<!-- www-lanes-sync:end -->"

SECTION_RE = re.compile(
    r"(## Pending proposals \(from www-feed\)\s*\n)(.*?)(?=\n## |\Z)",
    re.DOTALL,
)
LANE_SECTION_RE = re.compile(
    r"## Lane proposals\s*\n+(.*?)(?=\n## |\Z)",
    re.DOTALL,
)
ROW_RE = re.compile(
    r"^\|\s*`?([^`|]+?)`?\s*\|\s*([^|]*?)\s*\|\s*([^|]*?)\s*\|\s*$",
    re.MULTILINE,
)


def parse_lane_proposals(feed_text: str) -> list[tuple[str, str, str]]:
    m = LANE_SECTION_RE.search(feed_text)
    if not m:
        return []
    body = m.group(1)
    rows: list[tuple[str, str, str]] = []
    for match in ROW_RE.finditer(body):
        name, why, status = (c.strip() for c in match.groups())
        lower = name.lower()
        if lower in {"proposed lane", "--------", "---------------"}:
            continue
        if set(name) <= {"-"}:
            continue
        name = name.strip("`").strip()
        why = why.strip()
        status = (status.strip() or "proposal").lower()
        if not name:
            continue
        source = f"www-feed — {why}" if why else "www-feed"
        rows.append((name, source, status))
    return rows


def render_pending_block(rows: list[tuple[str, str, str]]) -> str:
    lines = [
        BEGIN,
        "",
        "| Proposed | Source | Status |",
        "|----------|--------|--------|",
    ]
    if not rows:
        lines.append("| _(none)_ | | |")
    else:
        for name, source, status in rows:
            lines.append(f"| `{name}` | {source} | {status} |")
    lines.extend(["", END, ""])
    return "\n".join(lines)


def expected_lanes_text(lanes_text: str, rows: list[tuple[str, str, str]]) -> str:
    block = render_pending_block(rows)
    m = SECTION_RE.search(lanes_text)
    if not m:
        raise SystemExit(
            "lanes.md missing '## Pending proposals (from www-feed)' section"
        )
    header = m.group(1)
    # Drop any hand-written blurb between header and markers; keep a one-line hint.
    hint = (
        "<!-- Generated by scripts/www-lanes-sync.py from www-feed Lane proposals. "
        "Do not hand-edit inside markers. -->\n\n"
    )
    replacement = header + hint + block
    return lanes_text[: m.start()] + replacement + lanes_text[m.end() :]


def sync(
    *,
    feed_path: Path,
    lanes_path: Path,
    check_only: bool,
) -> dict:
    if not feed_path.is_file():
        return {
            "ok": False,
            "changed": False,
            "error": f"feed not found: {feed_path}",
            "rows": 0,
        }
    if not lanes_path.is_file():
        return {
            "ok": False,
            "changed": False,
            "error": f"lanes not found: {lanes_path}",
            "rows": 0,
        }

    feed_text = feed_path.read_text(encoding="utf-8")
    lanes_text = lanes_path.read_text(encoding="utf-8")
    rows = parse_lane_proposals(feed_text)
    new_text = expected_lanes_text(lanes_text, rows)
    changed = new_text != lanes_text

    if check_only:
        return {
            "ok": not changed,
            "changed": changed,
            "error": "Pending proposals drift from www-feed" if changed else None,
            "rows": len(rows),
        }

    if changed:
        lanes_path.write_text(new_text, encoding="utf-8")

    return {
        "ok": True,
        "changed": changed,
        "error": None,
        "rows": len(rows),
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--feed",
        type=Path,
        default=DEFAULT_FEED,
        help="Absolute path to strategy www-feed.md",
    )
    ap.add_argument(
        "--lanes",
        type=Path,
        default=DEFAULT_LANES,
        help="Path to codex-www .cursor/lanes.md",
    )
    ap.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if Pending drifts; do not write",
    )
    ap.add_argument(
        "--json",
        action="store_true",
        help="Print result JSON on stdout",
    )
    args = ap.parse_args()

    result = sync(feed_path=args.feed, lanes_path=args.lanes, check_only=args.check)
    if args.json:
        print(json.dumps(result, sort_keys=True))
    elif result.get("error") and not result.get("ok"):
        print(result["error"], file=sys.stderr)
    elif result["changed"]:
        print(f"synced Pending proposals ({result['rows']} row(s))")
    else:
        print(f"Pending proposals already in sync ({result['rows']} row(s))")

    if args.check:
        return 0 if result["ok"] else 1
    return 0 if result["ok"] else 1


if __name__ == "__main__":
    sys.exit(main())
